### ISSUE TITLE
Eigenes JSON wird nicht geladen

### ISSUE THREAD

**Issue by IdeeAnhang** [Contao-DD/advanced-classes-bundle#1]
Wenn ich eine eigene JSON-Datei angelegt habe und in den Einstellungen ausgewählt, wird diese nicht übernommen.
In einer alten Version wurde dies in in der jquery.advanced_classes.js in Zeile 8 gesetzt:
`var sourceSet = advancedClassesSet || "bootstrap.json";`

**Comment by seibtph** [comment]
ist in der v0.4.0 behoben

**Comment by kgansberger** [comment]
wo muss die eigene *.json liegen?

**Comment by seibtph** [comment]
@kgansberger Die JSON-Datei kann überall liegen, z. B. im files-Ordner. Du musst das Set aber über die config.php einbinden.

Lege dazu folgende Datei an oder bearbeite sie: app/Resources/contao/config/config.php

Dort kannst du das Set wie folgt registrieren:

```
<?php

$GLOBALS['TL_CONFIG']['advancedClassesSets'][] = '/files/sets/custom-set.json';
```

Danach noch im Contao Manager den Cache leeren und anschließend solltest du das Set in den Einstellungen auswählen können.

**Comment by kgansberger** [comment]
@seibtph danke, ich habs bereits so gemacht , merci!!
