### ISSUE TITLE
additional set for Bootstrap5

### ISSUE THREAD

**Issue by MDevster** [Contao-DD/advanced-classes-bundle#18]
I wanted to create an additional set for Bootstrap5 because the xxl classes are missing in the set for Bootstrap4.

As described, I registered the set (copied the existing bootstrap4.json to avoid errors) and selected it in the settings.

But the selection is missing, as in the screenshot of @jedoCodes

_Originally posted by @fr4nk2342 in https://github.com/Contao-DD/advanced-classes-bundle/issues/16#issuecomment-1946020369_

**Comment by fr4nk2342** [comment]
Contao 5.3.0
Advanced Classes 1.5.3

I'd like to help with the BS5 File, but I can't use it. I copied the original BS4-File and renamed it. I can select ist, but there is no selection.

![image](https://github.com/Contao-DD/advanced-classes-bundle/assets/7665987/9354de91-f639-42bf-b276-dac053387bac)

![image](https://github.com/Contao-DD/advanced-classes-bundle/assets/7665987/76354770-68a3-4d98-a448-095cbb29f770)

**Comment by fr4nk2342** [comment]
my mistake, the folder wasn't public. Here's my file for Bootstrap 5 with xxl Breakpoints
[bootstrap5.json](https://github.com/Contao-DD/advanced-classes-bundle/files/14370974/bootstrap5.json)

**Comment by fr4nk2342** [comment]
@MDevster thx for adding bootstrap5 to config. but the json-file itself is missing. ;)

**Comment by MDevster** [comment]
Sorry, fixed in 1.6.1 ;)
