### ISSUE TITLE
Input to edit multiple elements is missing

### ISSUE THREAD

**Issue by fr4nk2342** [Contao-DD/advanced-classes-bundle#19]
Contao: 5.3
Advanced-Classes: 1.5.3

Input to edit multiple elements is missing

![image](https://github.com/Contao-DD/advanced-classes-bundle/assets/7665987/3c8cb514-18ce-4a27-832c-cec6aaadbeca)
![image](https://github.com/Contao-DD/advanced-classes-bundle/assets/7665987/f2135ef5-0ad7-4de8-bb5f-2a9c669a72ff)

**Comment by MDevster** [comment]
@fr4nk2342 Do you need the wizard for "edit multiple" or are the CSS classes sufficient?

![grafik](https://github.com/Contao-DD/advanced-classes-bundle/assets/10244240/ea3567eb-2afc-4826-9bcf-d6cec0670136)

**Comment by fr4nk2342** [comment]
@MDevster  CSS classes should be sufficient. This was also the case in the older versions and a useful feasture.

**Comment by MDevster** [comment]
Wir testen noch einmal alles, dann sollte es zeitnah veröffentlicht sein ;) 
https://github.com/Contao-DD/advanced-classes-bundle/pull/21
