### ISSUE TITLE
Wrong way to add jQuery to backend

### ISSUE THREAD

**Issue by MicioMax** [Contao-DD/advanced-classes-bundle#4]
Hi,
in config.php you've this code to add jQuery to the backend : 

```
/**
 * Backend Javascript
 */
if (TL_MODE == 'BE') {
    $GLOBALS['TL_JAVASCRIPT']['jquery'] = 'assets/jquery/js/jquery.min.js';
    $GLOBALS['TL_JAVASCRIPT']['noconflict'] = 'bundles/contaoddadvancedclasses/js/jquery.noconflict.js';
    $GLOBALS['TL_JAVASCRIPT']['advanced_classes'] = 'bundles/contaoddadvancedclasses/js/jquery.advanced_classes.js';
}
```

which doesn't test if any other package already added jQuery to it, which is, for example, the case for heimrichhannot/contao-haste_plus (which does indeed check if some other package did it already).
Your code moves the jQuery loading at the end of the list, making former packages to fail.
You should add some

`if(!isset($GLOBALS['TL_JAVASCRIPT']['jquery'])) { ...`

to check it before adding it.

**Comment by contaoacademy** [comment]
Wird das Problem noch behoben?

**Comment by seibtph** [comment]
Ist in Version 1.2.2 behoben.
